// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: par2vec.proto
#ifndef GRPC_par2vec_2eproto__INCLUDED
#define GRPC_par2vec_2eproto__INCLUDED

#include "par2vec.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace par2vec {

class Par2Vec final {
 public:
  static constexpr char const* service_full_name() {
    return "par2vec.Par2Vec";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status hello(::grpc::ClientContext* context, const ::par2vec::HelloRequest& request, ::par2vec::HelloReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::par2vec::HelloReply>> Asynchello(::grpc::ClientContext* context, const ::par2vec::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::par2vec::HelloReply>>(AsynchelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::par2vec::HelloReply>> PrepareAsynchello(::grpc::ClientContext* context, const ::par2vec::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::par2vec::HelloReply>>(PrepareAsynchelloRaw(context, request, cq));
    }
    virtual ::grpc::Status convertParToVec(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest& request, ::par2vec::DefaultReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::par2vec::DefaultReply>> AsyncconvertParToVec(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::par2vec::DefaultReply>>(AsyncconvertParToVecRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::par2vec::DefaultReply>> PrepareAsyncconvertParToVec(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::par2vec::DefaultReply>>(PrepareAsyncconvertParToVecRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void hello(::grpc::ClientContext* context, const ::par2vec::HelloRequest* request, ::par2vec::HelloReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void hello(::grpc::ClientContext* context, const ::par2vec::HelloRequest* request, ::par2vec::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void convertParToVec(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest* request, ::par2vec::DefaultReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void convertParToVec(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest* request, ::par2vec::DefaultReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::par2vec::HelloReply>* AsynchelloRaw(::grpc::ClientContext* context, const ::par2vec::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::par2vec::HelloReply>* PrepareAsynchelloRaw(::grpc::ClientContext* context, const ::par2vec::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::par2vec::DefaultReply>* AsyncconvertParToVecRaw(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::par2vec::DefaultReply>* PrepareAsyncconvertParToVecRaw(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status hello(::grpc::ClientContext* context, const ::par2vec::HelloRequest& request, ::par2vec::HelloReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::par2vec::HelloReply>> Asynchello(::grpc::ClientContext* context, const ::par2vec::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::par2vec::HelloReply>>(AsynchelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::par2vec::HelloReply>> PrepareAsynchello(::grpc::ClientContext* context, const ::par2vec::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::par2vec::HelloReply>>(PrepareAsynchelloRaw(context, request, cq));
    }
    ::grpc::Status convertParToVec(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest& request, ::par2vec::DefaultReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::par2vec::DefaultReply>> AsyncconvertParToVec(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::par2vec::DefaultReply>>(AsyncconvertParToVecRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::par2vec::DefaultReply>> PrepareAsyncconvertParToVec(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::par2vec::DefaultReply>>(PrepareAsyncconvertParToVecRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void hello(::grpc::ClientContext* context, const ::par2vec::HelloRequest* request, ::par2vec::HelloReply* response, std::function<void(::grpc::Status)>) override;
      void hello(::grpc::ClientContext* context, const ::par2vec::HelloRequest* request, ::par2vec::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void convertParToVec(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest* request, ::par2vec::DefaultReply* response, std::function<void(::grpc::Status)>) override;
      void convertParToVec(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest* request, ::par2vec::DefaultReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::par2vec::HelloReply>* AsynchelloRaw(::grpc::ClientContext* context, const ::par2vec::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::par2vec::HelloReply>* PrepareAsynchelloRaw(::grpc::ClientContext* context, const ::par2vec::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::par2vec::DefaultReply>* AsyncconvertParToVecRaw(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::par2vec::DefaultReply>* PrepareAsyncconvertParToVecRaw(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_hello_;
    const ::grpc::internal::RpcMethod rpcmethod_convertParToVec_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status hello(::grpc::ServerContext* context, const ::par2vec::HelloRequest* request, ::par2vec::HelloReply* response);
    virtual ::grpc::Status convertParToVec(::grpc::ServerContext* context, const ::par2vec::Par2VecRequest* request, ::par2vec::DefaultReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_hello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hello(::grpc::ServerContext* /*context*/, const ::par2vec::HelloRequest* /*request*/, ::par2vec::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requesthello(::grpc::ServerContext* context, ::par2vec::HelloRequest* request, ::grpc::ServerAsyncResponseWriter< ::par2vec::HelloReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_convertParToVec : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_convertParToVec() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_convertParToVec() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status convertParToVec(::grpc::ServerContext* /*context*/, const ::par2vec::Par2VecRequest* /*request*/, ::par2vec::DefaultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestconvertParToVec(::grpc::ServerContext* context, ::par2vec::Par2VecRequest* request, ::grpc::ServerAsyncResponseWriter< ::par2vec::DefaultReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_hello<WithAsyncMethod_convertParToVec<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_hello() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::par2vec::HelloRequest, ::par2vec::HelloReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::par2vec::HelloRequest* request, ::par2vec::HelloReply* response) { return this->hello(context, request, response); }));}
    void SetMessageAllocatorFor_hello(
        ::grpc::MessageAllocator< ::par2vec::HelloRequest, ::par2vec::HelloReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::par2vec::HelloRequest, ::par2vec::HelloReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hello(::grpc::ServerContext* /*context*/, const ::par2vec::HelloRequest* /*request*/, ::par2vec::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* hello(
      ::grpc::CallbackServerContext* /*context*/, const ::par2vec::HelloRequest* /*request*/, ::par2vec::HelloReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_convertParToVec : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_convertParToVec() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::par2vec::Par2VecRequest, ::par2vec::DefaultReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::par2vec::Par2VecRequest* request, ::par2vec::DefaultReply* response) { return this->convertParToVec(context, request, response); }));}
    void SetMessageAllocatorFor_convertParToVec(
        ::grpc::MessageAllocator< ::par2vec::Par2VecRequest, ::par2vec::DefaultReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::par2vec::Par2VecRequest, ::par2vec::DefaultReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_convertParToVec() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status convertParToVec(::grpc::ServerContext* /*context*/, const ::par2vec::Par2VecRequest* /*request*/, ::par2vec::DefaultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* convertParToVec(
      ::grpc::CallbackServerContext* /*context*/, const ::par2vec::Par2VecRequest* /*request*/, ::par2vec::DefaultReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_hello<WithCallbackMethod_convertParToVec<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_hello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hello(::grpc::ServerContext* /*context*/, const ::par2vec::HelloRequest* /*request*/, ::par2vec::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_convertParToVec : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_convertParToVec() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_convertParToVec() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status convertParToVec(::grpc::ServerContext* /*context*/, const ::par2vec::Par2VecRequest* /*request*/, ::par2vec::DefaultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_hello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hello(::grpc::ServerContext* /*context*/, const ::par2vec::HelloRequest* /*request*/, ::par2vec::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requesthello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_convertParToVec : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_convertParToVec() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_convertParToVec() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status convertParToVec(::grpc::ServerContext* /*context*/, const ::par2vec::Par2VecRequest* /*request*/, ::par2vec::DefaultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestconvertParToVec(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_hello() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->hello(context, request, response); }));
    }
    ~WithRawCallbackMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hello(::grpc::ServerContext* /*context*/, const ::par2vec::HelloRequest* /*request*/, ::par2vec::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* hello(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_convertParToVec : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_convertParToVec() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->convertParToVec(context, request, response); }));
    }
    ~WithRawCallbackMethod_convertParToVec() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status convertParToVec(::grpc::ServerContext* /*context*/, const ::par2vec::Par2VecRequest* /*request*/, ::par2vec::DefaultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* convertParToVec(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_hello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::par2vec::HelloRequest, ::par2vec::HelloReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::par2vec::HelloRequest, ::par2vec::HelloReply>* streamer) {
                       return this->Streamedhello(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status hello(::grpc::ServerContext* /*context*/, const ::par2vec::HelloRequest* /*request*/, ::par2vec::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedhello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::par2vec::HelloRequest,::par2vec::HelloReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_convertParToVec : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_convertParToVec() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::par2vec::Par2VecRequest, ::par2vec::DefaultReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::par2vec::Par2VecRequest, ::par2vec::DefaultReply>* streamer) {
                       return this->StreamedconvertParToVec(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_convertParToVec() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status convertParToVec(::grpc::ServerContext* /*context*/, const ::par2vec::Par2VecRequest* /*request*/, ::par2vec::DefaultReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedconvertParToVec(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::par2vec::Par2VecRequest,::par2vec::DefaultReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_hello<WithStreamedUnaryMethod_convertParToVec<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_hello<WithStreamedUnaryMethod_convertParToVec<Service > > StreamedService;
};

}  // namespace par2vec


#endif  // GRPC_par2vec_2eproto__INCLUDED
