// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: par2vec.proto

#include "par2vec.pb.h"
#include "par2vec.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace par2vec {

static const char* Par2Vec_method_names[] = {
  "/par2vec.Par2Vec/hello",
  "/par2vec.Par2Vec/convertParToVec",
};

std::unique_ptr< Par2Vec::Stub> Par2Vec::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Par2Vec::Stub> stub(new Par2Vec::Stub(channel, options));
  return stub;
}

Par2Vec::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_hello_(Par2Vec_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_convertParToVec_(Par2Vec_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Par2Vec::Stub::hello(::grpc::ClientContext* context, const ::par2vec::HelloRequest& request, ::par2vec::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::par2vec::HelloRequest, ::par2vec::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_hello_, context, request, response);
}

void Par2Vec::Stub::async::hello(::grpc::ClientContext* context, const ::par2vec::HelloRequest* request, ::par2vec::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::par2vec::HelloRequest, ::par2vec::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_hello_, context, request, response, std::move(f));
}

void Par2Vec::Stub::async::hello(::grpc::ClientContext* context, const ::par2vec::HelloRequest* request, ::par2vec::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_hello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::par2vec::HelloReply>* Par2Vec::Stub::PrepareAsynchelloRaw(::grpc::ClientContext* context, const ::par2vec::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::par2vec::HelloReply, ::par2vec::HelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_hello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::par2vec::HelloReply>* Par2Vec::Stub::AsynchelloRaw(::grpc::ClientContext* context, const ::par2vec::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Par2Vec::Stub::convertParToVec(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest& request, ::par2vec::DefaultReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::par2vec::Par2VecRequest, ::par2vec::DefaultReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_convertParToVec_, context, request, response);
}

void Par2Vec::Stub::async::convertParToVec(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest* request, ::par2vec::DefaultReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::par2vec::Par2VecRequest, ::par2vec::DefaultReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_convertParToVec_, context, request, response, std::move(f));
}

void Par2Vec::Stub::async::convertParToVec(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest* request, ::par2vec::DefaultReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_convertParToVec_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::par2vec::DefaultReply>* Par2Vec::Stub::PrepareAsyncconvertParToVecRaw(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::par2vec::DefaultReply, ::par2vec::Par2VecRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_convertParToVec_, context, request);
}

::grpc::ClientAsyncResponseReader< ::par2vec::DefaultReply>* Par2Vec::Stub::AsyncconvertParToVecRaw(::grpc::ClientContext* context, const ::par2vec::Par2VecRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncconvertParToVecRaw(context, request, cq);
  result->StartCall();
  return result;
}

Par2Vec::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Par2Vec_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Par2Vec::Service, ::par2vec::HelloRequest, ::par2vec::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Par2Vec::Service* service,
             ::grpc::ServerContext* ctx,
             const ::par2vec::HelloRequest* req,
             ::par2vec::HelloReply* resp) {
               return service->hello(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Par2Vec_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Par2Vec::Service, ::par2vec::Par2VecRequest, ::par2vec::DefaultReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Par2Vec::Service* service,
             ::grpc::ServerContext* ctx,
             const ::par2vec::Par2VecRequest* req,
             ::par2vec::DefaultReply* resp) {
               return service->convertParToVec(ctx, req, resp);
             }, this)));
}

Par2Vec::Service::~Service() {
}

::grpc::Status Par2Vec::Service::hello(::grpc::ServerContext* context, const ::par2vec::HelloRequest* request, ::par2vec::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Par2Vec::Service::convertParToVec(::grpc::ServerContext* context, const ::par2vec::Par2VecRequest* request, ::par2vec::DefaultReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace par2vec

