definitions:
  main.Par2VecRequest:
    properties:
      paragraph:
        type: string
    type: object
  main.Par2VecResponse:
    properties:
      dim:
        type: integer
      fvec:
        items:
          type: number
        type: array
    type: object
  main.SearchFreelancerResponse:
    properties:
      D:
        items:
          type: number
        type: array
      message:
        type: string
      name:
        items:
          type: string
        type: array
      numNeighbors:
        type: integer
      numQueryVectors:
        type: integer
      status:
        type: string
    type: object
  main.SearchProjectResponse:
    properties:
      D:
        items:
          type: number
        type: array
      message:
        type: string
      name:
        items:
          type: string
        type: array
      numNeighbors:
        type: integer
      numQueryVectors:
        type: integer
      status:
        type: string
    type: object
  main.SimpleResponse:
    properties:
      message:
        type: string
    type: object
  main.VsDefaultRequest:
    properties:
      indexName:
        type: string
    type: object
  main.VsDefaultResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  main.VsIndexList:
    properties:
      dim:
        items:
          type: integer
        type: array
      indexName:
        items:
          type: string
        type: array
      numVectors:
        items:
          type: integer
        type: array
    type: object
  main.VsSearchRequest:
    properties:
      dim:
        type: integer
      indexName:
        type: string
      numNeighbors:
        type: integer
      numQueryVectors:
        type: integer
      vecData:
        items:
          type: number
        type: array
    type: object
  main.VsSearchResponse:
    properties:
      D:
        items:
          type: number
        type: array
      I:
        items:
          type: integer
        type: array
      message:
        type: string
      numNeighbors:
        type: integer
      numQueryVectors:
        type: integer
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /freelancer/{id}/find/projects:
    get:
      consumes:
      - application/json
      description: Find freelancers clost to a given project
      parameters:
      - description: Freelancer Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Found projects close to the input freelancer
          schema:
            $ref: '#/definitions/main.SearchProjectResponse'
        "400":
          description: Freelancer ID missing in the path
          schema:
            $ref: '#/definitions/main.VsDefaultResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/main.VsDefaultResponse'
      summary: Find projects
      tags:
      - Search
  /index/getList:
    get:
      consumes:
      - application/json
      description: Get a list of all loaded indices
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.VsIndexList'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/main.VsDefaultResponse'
      summary: Get a list of all loadded indices
      tags:
      - Index
  /index/load:
    post:
      consumes:
      - application/json
      description: Load index from DB to memory
      parameters:
      - description: Default request
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/main.VsDefaultRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Loaded index
          schema:
            $ref: '#/definitions/main.VsDefaultResponse'
        "400":
          description: Name parameter required
          schema:
            $ref: '#/definitions/main.VsDefaultResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/main.VsDefaultResponse'
      summary: Load index
      tags:
      - Index
  /index/search:
    post:
      consumes:
      - application/json
      description: Find neighbor items for a given feature vector
      parameters:
      - description: Search request
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/main.VsSearchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Found neighbors close to the input feature vector
          schema:
            $ref: '#/definitions/main.VsSearchResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.VsSearchResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/main.VsSearchResponse'
      summary: Find neighbor items for a given feature vector
      tags:
      - Index
  /index/unload:
    post:
      consumes:
      - application/json
      description: Unload index from memory
      parameters:
      - description: Default request
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/main.VsDefaultRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Unloaded index
          schema:
            $ref: '#/definitions/main.VsDefaultResponse'
        "400":
          description: Name parameter required
          schema:
            $ref: '#/definitions/main.VsDefaultResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/main.VsDefaultResponse'
      summary: Unload index
      tags:
      - Index
  /par2vec:
    post:
      consumes:
      - application/json
      description: Convert a paragraph to feature vector
      parameters:
      - description: Paragraph
        in: body
        name: paragraph
        required: true
        schema:
          $ref: '#/definitions/main.Par2VecRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully converted paragraph to feature vector
          schema:
            $ref: '#/definitions/main.Par2VecResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/main.SimpleResponse'
      summary: Convert a paragraph to feature vector
      tags:
      - Par2Vec
  /projects/{id}/find/freelancers:
    get:
      consumes:
      - application/json
      description: Find freelancers clost to a given project
      parameters:
      - description: Project Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Found freelancers close to the input project
          schema:
            $ref: '#/definitions/main.SearchFreelancerResponse'
        "400":
          description: Project ID missing in the path
          schema:
            $ref: '#/definitions/main.VsDefaultResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/main.VsDefaultResponse'
      summary: Find freelancers
      tags:
      - Search
swagger: "2.0"
