// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.4
// source: proto/par2vec.proto

package par2vec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Par2VecRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paragraph string `protobuf:"bytes,1,opt,name=paragraph,proto3" json:"paragraph,omitempty"`
}

func (x *Par2VecRequest) Reset() {
	*x = Par2VecRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_par2vec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Par2VecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Par2VecRequest) ProtoMessage() {}

func (x *Par2VecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_par2vec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Par2VecRequest.ProtoReflect.Descriptor instead.
func (*Par2VecRequest) Descriptor() ([]byte, []int) {
	return file_proto_par2vec_proto_rawDescGZIP(), []int{0}
}

func (x *Par2VecRequest) GetParagraph() string {
	if x != nil {
		return x.Paragraph
	}
	return ""
}

type DefaultReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dim  uint32    `protobuf:"varint,1,opt,name=dim,proto3" json:"dim,omitempty"`
	FVec []float32 `protobuf:"fixed32,2,rep,packed,name=fVec,proto3" json:"fVec,omitempty"`
}

func (x *DefaultReply) Reset() {
	*x = DefaultReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_par2vec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultReply) ProtoMessage() {}

func (x *DefaultReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_par2vec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultReply.ProtoReflect.Descriptor instead.
func (*DefaultReply) Descriptor() ([]byte, []int) {
	return file_proto_par2vec_proto_rawDescGZIP(), []int{1}
}

func (x *DefaultReply) GetDim() uint32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *DefaultReply) GetFVec() []float32 {
	if x != nil {
		return x.FVec
	}
	return nil
}

var File_proto_par2vec_proto protoreflect.FileDescriptor

var file_proto_par2vec_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x72, 0x32, 0x76, 0x65, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x61, 0x72, 0x32, 0x76, 0x65, 0x63, 0x22, 0x2e,
	0x0a, 0x0e, 0x50, 0x61, 0x72, 0x32, 0x56, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x61, 0x67, 0x72, 0x61, 0x70, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x72, 0x61, 0x67, 0x72, 0x61, 0x70, 0x68, 0x22, 0x34,
	0x0a, 0x0c, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x69, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x64, 0x69, 0x6d,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x56, 0x65, 0x63, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x04,
	0x66, 0x56, 0x65, 0x63, 0x32, 0x4e, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x32, 0x56, 0x65, 0x63, 0x12,
	0x43, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x50, 0x61, 0x72, 0x54, 0x6f, 0x56,
	0x65, 0x63, 0x12, 0x17, 0x2e, 0x70, 0x61, 0x72, 0x32, 0x76, 0x65, 0x63, 0x2e, 0x50, 0x61, 0x72,
	0x32, 0x56, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x61,
	0x72, 0x32, 0x76, 0x65, 0x63, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x61, 0x72, 0x32, 0x76, 0x65, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_par2vec_proto_rawDescOnce sync.Once
	file_proto_par2vec_proto_rawDescData = file_proto_par2vec_proto_rawDesc
)

func file_proto_par2vec_proto_rawDescGZIP() []byte {
	file_proto_par2vec_proto_rawDescOnce.Do(func() {
		file_proto_par2vec_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_par2vec_proto_rawDescData)
	})
	return file_proto_par2vec_proto_rawDescData
}

var file_proto_par2vec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_par2vec_proto_goTypes = []any{
	(*Par2VecRequest)(nil), // 0: par2vec.Par2VecRequest
	(*DefaultReply)(nil),   // 1: par2vec.DefaultReply
}
var file_proto_par2vec_proto_depIdxs = []int32{
	0, // 0: par2vec.Par2Vec.convertParToVec:input_type -> par2vec.Par2VecRequest
	1, // 1: par2vec.Par2Vec.convertParToVec:output_type -> par2vec.DefaultReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_par2vec_proto_init() }
func file_proto_par2vec_proto_init() {
	if File_proto_par2vec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_par2vec_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Par2VecRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_par2vec_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DefaultReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_par2vec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_par2vec_proto_goTypes,
		DependencyIndexes: file_proto_par2vec_proto_depIdxs,
		MessageInfos:      file_proto_par2vec_proto_msgTypes,
	}.Build()
	File_proto_par2vec_proto = out.File
	file_proto_par2vec_proto_rawDesc = nil
	file_proto_par2vec_proto_goTypes = nil
	file_proto_par2vec_proto_depIdxs = nil
}
