// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.4
// source: proto/par2vec.proto

package par2vec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Par2Vec_ConvertParToVec_FullMethodName = "/par2vec.Par2Vec/convertParToVec"
)

// Par2VecClient is the client API for Par2Vec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Par2VecClient interface {
	ConvertParToVec(ctx context.Context, in *Par2VecRequest, opts ...grpc.CallOption) (*DefaultReply, error)
}

type par2VecClient struct {
	cc grpc.ClientConnInterface
}

func NewPar2VecClient(cc grpc.ClientConnInterface) Par2VecClient {
	return &par2VecClient{cc}
}

func (c *par2VecClient) ConvertParToVec(ctx context.Context, in *Par2VecRequest, opts ...grpc.CallOption) (*DefaultReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefaultReply)
	err := c.cc.Invoke(ctx, Par2Vec_ConvertParToVec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Par2VecServer is the server API for Par2Vec service.
// All implementations must embed UnimplementedPar2VecServer
// for forward compatibility.
type Par2VecServer interface {
	ConvertParToVec(context.Context, *Par2VecRequest) (*DefaultReply, error)
	mustEmbedUnimplementedPar2VecServer()
}

// UnimplementedPar2VecServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPar2VecServer struct{}

func (UnimplementedPar2VecServer) ConvertParToVec(context.Context, *Par2VecRequest) (*DefaultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertParToVec not implemented")
}
func (UnimplementedPar2VecServer) mustEmbedUnimplementedPar2VecServer() {}
func (UnimplementedPar2VecServer) testEmbeddedByValue()                 {}

// UnsafePar2VecServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Par2VecServer will
// result in compilation errors.
type UnsafePar2VecServer interface {
	mustEmbedUnimplementedPar2VecServer()
}

func RegisterPar2VecServer(s grpc.ServiceRegistrar, srv Par2VecServer) {
	// If the following call pancis, it indicates UnimplementedPar2VecServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Par2Vec_ServiceDesc, srv)
}

func _Par2Vec_ConvertParToVec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Par2VecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Par2VecServer).ConvertParToVec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Par2Vec_ConvertParToVec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Par2VecServer).ConvertParToVec(ctx, req.(*Par2VecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Par2Vec_ServiceDesc is the grpc.ServiceDesc for Par2Vec service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Par2Vec_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "par2vec.Par2Vec",
	HandlerType: (*Par2VecServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "convertParToVec",
			Handler:    _Par2Vec_ConvertParToVec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/par2vec.proto",
}
