# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: par2vec.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'par2vec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpar2vec.proto\x12\x0brecommender\"#\n\x0ePar2VecRequest\x12\x11\n\tparagraph\x18\x01 \x01(\t\")\n\x0c\x44\x65\x66\x61ultReply\x12\x0b\n\x03\x64im\x18\x01 \x01(\r\x12\x0c\n\x04\x66Vec\x18\x02 \x03(\x02\x32V\n\x07Par2Vec\x12K\n\x0f\x63onvertParToVec\x12\x1b.recommender.Par2VecRequest\x1a\x19.recommender.DefaultReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'par2vec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAR2VECREQUEST']._serialized_start=30
  _globals['_PAR2VECREQUEST']._serialized_end=65
  _globals['_DEFAULTREPLY']._serialized_start=67
  _globals['_DEFAULTREPLY']._serialized_end=108
  _globals['_PAR2VEC']._serialized_start=110
  _globals['_PAR2VEC']._serialized_end=196
# @@protoc_insertion_point(module_scope)
